name: CI

on:
  push:
    branches:
      - Release-Test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSVC
      uses: microsoft/setup-msvc@v1
      with:
        msvc-version: '2022'

    - name: Build
      run: msbuild /p:Configuration=Release PetSalut.sln
