name: CI

on:
  push:
    branches:
      - Release-Test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSVC environment
      uses: microsoft/setup-msbuild@main

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Build solution
      run: msbuild /p:Configuration=Release PetSalut.sln
